"""Model-independent contracts and policies for the first RAG design phase."""

from .chunking import ChunkingConfig, chunk_document
from .citation import build_citation, citation_url_for_document, sanitize_public_url
from .contracts import (
    SCHEMA_VERSION,
    AbstentionReason,
    AnswerResult,
    Chunk,
    ClaimCheck,
    Citation,
    Document,
    EvidenceCheckResult,
    EvidenceStatus,
    RetrievedChunk,
    Section,
    SensitiveDataStatus,
    SourceType,
    compute_content_hash,
    compute_document_id,
)
from .embeddings import (
    EmbeddingProvider,
    EmbeddingProviderError,
    HashEmbeddingProvider,
    SentenceTransformerKoreanProvider,
)
from .policy import AbstentionDecision, EvidenceState, decide_abstention
from .validation import (
    HandoffReport,
    validate_answer_evidence,
    validate_chunk_batch,
    validate_collection_handoff,
    validate_evidence_check_result,
)
from .vector_store import (
    ChromaUnavailableError,
    ChromaVectorStore,
    CollectionFingerprintMismatch,
    CollectionNotFoundError,
    CorruptVectorRecordError,
    SnapshotDeleteResult,
    SnapshotSyncResult,
    VectorSearchFilter,
    VectorStoreConfig,
    VectorStoreError,
)

__all__ = [
    "SCHEMA_VERSION",
    "AbstentionDecision",
    "AbstentionReason",
    "AnswerResult",
    "Chunk",
    "ChunkingConfig",
    "ClaimCheck",
    "Citation",
    "Document",
    "EmbeddingProvider",
    "EmbeddingProviderError",
    "EvidenceCheckResult",
    "EvidenceState",
    "EvidenceStatus",
    "HandoffReport",
    "HashEmbeddingProvider",
    "RetrievedChunk",
    "Section",
    "SensitiveDataStatus",
    "SentenceTransformerKoreanProvider",
    "SourceType",
    "ChromaUnavailableError",
    "ChromaVectorStore",
    "CollectionFingerprintMismatch",
    "CollectionNotFoundError",
    "CorruptVectorRecordError",
    "SnapshotDeleteResult",
    "SnapshotSyncResult",
    "VectorSearchFilter",
    "VectorStoreConfig",
    "VectorStoreError",
    "build_citation",
    "chunk_document",
    "citation_url_for_document",
    "compute_content_hash",
    "compute_document_id",
    "decide_abstention",
    "sanitize_public_url",
    "validate_answer_evidence",
    "validate_collection_handoff",
    "validate_chunk_batch",
    "validate_evidence_check_result",
]
